/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfSubscriptionInfo struct {
	OcfInstanceId string `json:"ocfInstanceId" bson:"ocfInstanceId"`
	// string providing an URI formatted according to IETF RFC 3986.
	SubscriptionId                string `json:"subscriptionId" bson:"subscriptionId"`
	SubsChangeNotifyCorrelationId string `json:"subsChangeNotifyCorrelationId,omitempty" bson:"subsChangeNotifyCorrelationId"`
}
