/*
 * Nocf_EventExposure
 *
 * OCF Event Exposure Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfUpdateEventSubscriptionItemInner struct {
	Op    string    `json:"op" bson:"op" `
	Path  string    `json:"path" bson:"path" `
	Value *OcfEvent `json:"value,omitempty" bson:"value" `
}
