/*
 * Nocf_Communication
 *
 * OCF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfEvent struct {
	Type                     OcfEventType           `json:"type"`
	ImmediateFlag            bool                   `json:"immediateFlag,omitempty"`
	AreaList                 []OcfEventArea         `json:"areaList,omitempty"`
	LocationFilterList       []LocationFilter       `json:"locationFilterList,omitempty"`
	SubscribedDataFilterList []SubscribedDataFilter `json:"subscribedDataFilterList,omitempty"`
}
