/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Ocf3GppAccessRegistration struct {
	OcfInstanceId     string  `json:"ocfInstanceId" bson:"ocfInstanceId"`
	SupportedFeatures string  `json:"supportedFeatures,omitempty" bson:"supportedFeatures"`
	PurgeFlag         bool    `json:"purgeFlag,omitempty" bson:"purgeFlag"`
	Pei               string  `json:"pei,omitempty" bson:"pei"`
	ImsVoPs           ImsVoPs `json:"imsVoPs,omitempty" bson:"imsVoPs"`
	// string providing an URI formatted according to IETF RFC 3986.
	DeregCallbackUri    string      `json:"deregCallbackUri" bson:"deregCallbackUri"`
	OcfServiceNameDereg ServiceName `json:"ocfServiceNameDereg,omitempty" bson:"ocfServiceNameDereg"`
	// string providing an URI formatted according to IETF RFC 3986.
	PcscfRestorationCallbackUri string          `json:"pcscfRestorationCallbackUri,omitempty" bson:"pcscfRestorationCallbackUri"`
	OcfServiceNamePcscfRest     ServiceName     `json:"ocfServiceNamePcscfRest,omitempty" bson:"ocfServiceNamePcscfRest"`
	InitialRegistrationInd      bool            `json:"initialRegistrationInd,omitempty" bson:"initialRegistrationInd"`
	Guami                       *Guami          `json:"guami" bson:"guami"`
	BackupOcfInfo               []BackupOcfInfo `json:"backupOcfInfo,omitempty" bson:"backupOcfInfo"`
	DrFlag                      bool            `json:"drFlag,omitempty" bson:"drFlag"`
	RatType                     RatType         `json:"ratType" bson:"ratType"`
}
