/*
 * Nocf_EventExposure
 *
 * OCF Event Exposure Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfCreatedEventSubscription struct {
	Subscription      *OcfEventSubscription `json:"subscription" bson:"subscription" `
	SubscriptionId    string                `json:"subscriptionId" bson:"subscriptionId" `
	ReportList        []OcfEventReport      `json:"reportList,omitempty" bson:"reportList" `
	SupportedFeatures string                `json:"supportedFeatures,omitempty" bson:"supportedFeatures" `
}
