/*
 * Nocf_Communication
 *
 * OCF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfEventTrigger string

// List of OcfEventTrigger
const (
	OcfEventTrigger_ONE_TIME   OcfEventTrigger = "ONE_TIME"
	OcfEventTrigger_CONTINUOUS OcfEventTrigger = "CONTINUOUS"
)
