/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type N2InterfaceOcfInfo struct {
	Ipv4EndpointAddress []string `json:"ipv4EndpointAddress,omitempty" yaml:"ipv4EndpointAddress" bson:"ipv4EndpointAddress" mapstructure:"Ipv4EndpointAddress"`
	Ipv6EndpointAddress []string `json:"ipv6EndpointAddress,omitempty" yaml:"ipv6EndpointAddress" bson:"ipv6EndpointAddress" mapstructure:"Ipv6EndpointAddress"`
	OcfName             string   `json:"ocfName,omitempty" yaml:"ocfName" bson:"ocfName" mapstructure:"OcfName"`
}
