/*
 * Nocf_Communication
 *
 * OCF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfEventType string

// List of OcfEventType
const (
	OcfEventType_LOCATION_REPORT              OcfEventType = "LOCATION_REPORT"
	OcfEventType_PRESENCE_IN_AOI_REPORT       OcfEventType = "PRESENCE_IN_AOI_REPORT"
	OcfEventType_TIMEZONE_REPORT              OcfEventType = "TIMEZONE_REPORT"
	OcfEventType_ACCESS_TYPE_REPORT           OcfEventType = "ACCESS_TYPE_REPORT"
	OcfEventType_REGISTRATION_STATE_REPORT    OcfEventType = "REGISTRATION_STATE_REPORT"
	OcfEventType_CONNECTIVITY_STATE_REPORT    OcfEventType = "CONNECTIVITY_STATE_REPORT"
	OcfEventType_REACHABILITY_REPORT          OcfEventType = "REACHABILITY_REPORT"
	OcfEventType_SUBSCRIBED_DATA_REPORT       OcfEventType = "SUBSCRIBED_DATA_REPORT"
	OcfEventType_COMMUNICATION_FAILURE_REPORT OcfEventType = "COMMUNICATION_FAILURE_REPORT"
	OcfEventType_UES_IN_AREA_REPORT           OcfEventType = "UES_IN_AREA_REPORT"
	OcfEventType_SUBSCRIPTION_ID_CHANGE       OcfEventType = "SUBSCRIPTION_ID_CHANGE"
	OcfEventType_SUBSCRIPTION_ID_ADDITION     OcfEventType = "SUBSCRIPTION_ID_ADDITION"
)
