/*
 * Nocf_EventExposure
 *
 * OCF Event Exposure Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfEventNotification struct {
	NotifyCorrelationId           string           `json:"notifyCorrelationId,omitempty" bson:"notifyCorrelationId" `
	SubsChangeNotifyCorrelationId string           `json:"subsChangeNotifyCorrelationId,omitempty" bson:"subsChangeNotifyCorrelationId" `
	ReportList                    []OcfEventReport `json:"reportList,omitempty" bson:"reportList" `
}
