/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Ocf3GppAccessRegistrationModification struct {
	Guami         *Guami          `json:"guami" bson:"guami"`
	PurgeFlag     bool            `json:"purgeFlag,omitempty" bson:"purgeFlag"`
	Pei           string          `json:"pei,omitempty" bson:"pei"`
	ImsVoPs       ImsVoPs         `json:"imsVoPs,omitempty" bson:"imsVoPs"`
	BackupOcfInfo []BackupOcfInfo `json:"backupOcfInfo,omitempty" bson:"backupOcfInfo"`
}
