/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfInfo struct {
	OcfSetId             string              `json:"ocfSetId" yaml:"ocfSetId" bson:"ocfSetId" mapstructure:"OcfSetId"`
	OcfRegionId          string              `json:"ocfRegionId" yaml:"ocfRegionId" bson:"ocfRegionId" mapstructure:"OcfRegionId"`
	GuamiList            *[]Guami            `json:"guamiList" yaml:"guamiList" bson:"guamiList" mapstructure:"GuamiList"`
	TaiList              *[]Tai              `json:"taiList,omitempty" yaml:"taiList" bson:"taiList" mapstructure:"TaiList"`
	TaiRangeList         *[]TaiRange         `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList" mapstructure:"TaiRangeList"`
	BackupInfoOcfFailure *[]Guami            `json:"backupInfoOcfFailure,omitempty" yaml:"backupInfoOcfFailure" bson:"backupInfoOcfFailure" mapstructure:"BackupInfoOcfFailure"`
	BackupInfoOcfRemoval *[]Guami            `json:"backupInfoOcfRemoval,omitempty" yaml:"backupInfoOcfRemoval" bson:"backupInfoOcfRemoval" mapstructure:"BackupInfoOcfRemoval"`
	N2InterfaceOcfInfo   *N2InterfaceOcfInfo `json:"n2InterfaceOcfInfo,omitempty" yaml:"n2InterfaceOcfInfo" bson:"n2InterfaceOcfInfo" mapstructure:"N2InterfaceOcfInfo"`
}
