/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfCond struct {
	OcfSetId    string `json:"ocfSetId,omitempty" yaml:"ocfSetId" bson:"ocfSetId" mapstructure:"OcfSetId"`
	OcfRegionId string `json:"ocfRegionId,omitempty" yaml:"ocfRegionId" bson:"ocfRegionId" mapstructure:"OcfRegionId"`
}
