/*
 * Nocf_Communication
 *
 * OCF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type OcfStatusChangeNotification struct {
	OcfStatusInfoList []OcfStatusInfo `json:"ocfStatusInfoList,omitempty"`
}
