/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type BackupOcfInfo struct {
	BackupOcf string  `json:"backupOcf" yaml:"backupOcf" bson:"backupOcf" mapstructure:"BackupOcf"`
	GuamiList []Guami `json:"guamiList,omitempty" yaml:"guamiList" bson:"guamiList" mapstructure:"GuamiList"`
}
